### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by youta19851124** [youta19851124/protospace-39694#1]
＃URL

https://protospace-39694.onrender.com/

**Comment by shodai-ito** [comment]
@youta19851124 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
### **`投稿機能`**
- [x] **画像は1枚必須であること(ActiveStorageを使用)**
画像がなくても投稿できてしまいます。

### **`一覧機能`**
- [x] **ログイン・ログアウトの状態に関わらず、一覧表示されている画像およびプロトタイプ名をクリックすると、該当するプロトタイプの詳細ページへ遷移すること**
画像から遷移はできますが、プロトタイプ名をクリックしても詳細ページに遷移できません。

### **`コメント機能`**
- [x] **コメント投稿欄は、ログイン状態のユーザーへのみ、詳細ページに表示されていること**
ログイン状態でも、自身が投稿していないプロトタイプにはコメントができなくなっています。

### **`ユーザー詳細機能`**
- [x] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移すること**
トップページにログインユーザー名、プロトタイプ詳細ページのプロトタイプ投稿者名をクリックしてもユーザー詳細ページに遷移できません。

### **`その他`**
- [x] **ログアウト状態のユーザーは、プロトタイプ新規投稿ページ・プロトタイプ編集ページに遷移しようとすると、ログインページにリダイレクトされること**
ログインページでなく、トップページに遷移してしまいます。
【チェック方法】
最初にログアウト状態を作る。投稿ページ・編集ページのURLを打ち込み、ログインページにリダイレクトされれば正常な挙動。

- [x] **ログイン状態のユーザーであっても、他のユーザーのプロトタイプ編集ページのURLを直接入力して遷移しようとすると、トップページにリダイレクトされること**
他人のプロトタイプも編集できてしまいます。
【チェック方法】
先ず、ユーザーAで投稿したプロトタイプの編集ページURLをコピー。
次に、ユーザーBでログインし、そのURLを直接入力した際に、トップページへリダイレクトされれば正常な挙動。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by mo1015** [comment]
@youta19851124 さん、再提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
